// examples/kit-nextjs-skate-park/src/components/link-list/LinkList.tsx
import React from 'react';
import { Text, LinkField } from '@sitecore-content-sdk/nextjs';
import { CompatibleLink } from 'components/content-sdk/CompatibleLink';
import { getDatasource } from 'lib/component-props';
import { LinkListItemProps, LinkListProps } from './link-list.props';

const LinkListItem = ({ index, total, field }: LinkListItemProps) => {
  const classNames = [
    `item${index}`,
    index % 2 === 0 ? 'odd' : 'even',
    index === 0 ? 'first' : '',
    index === total - 1 ? 'last' : '',
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <li className={classNames}>
      <div className="field-link">
        <CompatibleLink field={field} />
      </div>
    </li>
  );
};

export const Default = ({ params, fields }: LinkListProps) => {
  const datasource = getDatasource(fields);
  const styles = `component link-list ${params.styles || ''}`.trim();
  const id = params.RenderingIdentifier;

  const renderContent = () => {
    const results = datasource?.children?.results;

    if (!datasource || !Array.isArray(results)) {
      return <h3>Link List</h3>;
    }

    const links = results
      .filter((element): element is typeof element & { field: { link: LinkField } } =>
        Boolean(element?.field?.link)
      )
      .map((element, index) => (
        <LinkListItem
          key={`${index}-${element.field.link.value?.href ?? index}`}
          index={index}
          total={results.length}
          field={element.field.link}
        />
      ));

    return (
      <>
        <Text tag="h3" field={datasource.field?.title} />
        <ul>{links}</ul>
      </>
    );
  };

  return (
    <aside className={styles} id={id}>
      <div className="component-content">{renderContent()}</div>
    </aside>
  );
};

// examples/angular/src/app/components/link-list.component.ts
import { Component, computed } from '@angular/core';
import { isFieldValueEmpty } from '@sitecore-content-sdk/content/layout';
import { Field, ScTextDirective, ScLinkDirective, LinkField } from '@sitecore-content-sdk/angular';
import { SxaComponent } from './content-sdk/sxa.component';

interface LinkListDatasource {
  children?: {
    results?: Array<{
      field?: {
        link?: LinkField;
      };
    }>;
  };
  field?: {
    title?: Field<string>;
  };
}

interface LinkListFields {
  data?: { datasource?: LinkListDatasource };
}

@Component({
  selector: 'app-link-list',
  imports: [ScTextDirective, ScLinkDirective],
  host: {
    '[attr.class]': "('component link-list ' + styles().trim())",
    '[attr.id]': 'renderingId()',
  },
  template: `
    <div class="component-content">
      @if (!datasource()) {
      <h3>Link List</h3>
      } @else {
      <h3 *scText="titleField()"></h3>
      <ul>
        @for (row of linkRows(); track $index) {
        <li [class]="itemClass($index, linkRows().length)">
          <div class="field-link">
            <a *scLink="row.link"></a>
          </div>
        </li>
        }
      </ul>
      }
    </div>
  `,
})
export class LinkListComponent extends SxaComponent {
  readonly data = computed(() => (this.fields() as LinkListFields)?.data);

  readonly datasource = computed(() => this.data()?.datasource);

  readonly titleField = computed(() => this.datasource()?.field?.title);

  readonly linkRows = computed(() => {
    const results = this.datasource()?.children?.results;
    if (!Array.isArray(results)) return [] as Array<{ link: LinkField }>;
    return results
      .filter((result) => {
        const link = result?.field?.link;
        return !!link && !isFieldValueEmpty(link);
      })
      .map((result) => ({ link: result.field!.link! }));
  });

  /** SXA-style list row classes: `item{n}`, alternating odd/even (0-based), optional first/last. */
  itemClass(index: number, total: number): string {
    const classes = [`item${index}`, index % 2 === 0 ? 'odd' : 'even'];
    if (index === 0) classes.push('first');
    if (index === total - 1) classes.push('last');
    return classes.join(' ');
  }
}

export default LinkListComponent;
