// examples/kit-nextjs-skate-park/src/components/title/Title.tsx
import React, { JSX } from 'react';
import { LinkField, Text, TextField } from '@sitecore-content-sdk/nextjs';
import { CompatibleLink } from 'components/content-sdk/CompatibleLink';
import { getDatasource, getFieldValue } from 'lib/component-props';
import { TitleComponentContentProps, TitleProps } from './title.props';

const ComponentContent = ({ id, styles = '', children }: TitleComponentContentProps): JSX.Element => (
  <div className={`component title ${styles.trim()}`} id={id}>
    <div className="component-content">
      <div className="field-title">{children}</div>
    </div>
  </div>
);

export const Default = ({ params, fields, page }: TitleProps): JSX.Element => {
  const { styles, RenderingIdentifier: id } = params;
  const datasource = getDatasource(fields);
  const datasourceField = getFieldValue(datasource?.field) as TextField | undefined;
  const contextField: TextField = page?.layout?.sitecore?.route?.fields?.Title as TextField;
  const titleField: TextField = datasourceField || contextField;

  const link: LinkField = {
    value: {
      href: datasource?.url?.path,
      title:
        (titleField?.value ? String(titleField.value) : undefined) ||
        datasourceField?.value?.toString(),
    },
  };

  return (
    <ComponentContent styles={styles} id={id}>
      {page?.mode?.isEditing ? (
        <Text field={titleField} />
      ) : (
        <CompatibleLink field={link}>
          <Text field={titleField} />
        </CompatibleLink>
      )}
    </ComponentContent>
  );
};

// examples/angular/src/app/components/title.component.ts
import { Component, computed, inject } from '@angular/core';
import {
  Field,
  LinkField,
  ScLinkDirective,
  ScTextDirective,
  SitecoreContextService,
} from '@sitecore-content-sdk/angular';
import { SxaComponent } from './content-sdk/sxa.component';

interface GraphqlItem {
  url?: { path?: string; siteName?: string };
  field?: { jsonValue?: unknown };
}

interface TitleFields {
  data?: { datasource?: GraphqlItem; contextItem?: GraphqlItem };
}

@Component({
  selector: 'app-title',
  imports: [ScTextDirective, ScLinkDirective],
  host: {
    '[attr.class]': "('component title ' + styles().trim())",
    '[attr.id]': 'renderingId()',
  },
  template: `
    <div class="component-content">
      <div class="field-title">
        @if (isEditing()) {
        <span *scText="titleField()"></span>
        } @else {
        <a *scLink="titleLinkField()"><span *scText="titleField()"></span></a>
        }
      </div>
    </div>
  `,
})
export class TitleComponent extends SxaComponent {
  private readonly context = inject(SitecoreContextService);

  readonly fieldData = computed(() => (this.fields() as TitleFields)?.data);

  readonly datasource = computed(
    () => this.fieldData()?.datasource || this.fieldData()?.contextItem
  );

  readonly titleField = computed((): Field<string> | undefined => {
    const jsonVal = this.datasource()?.field?.jsonValue as Field<string> | undefined;
    if (jsonVal) {
      return jsonVal;
    }
    const route = this.context.page()?.layout?.sitecore?.route;
    return route?.fields?.Title as Field<string> | undefined;
  });

  readonly titleLinkField = computed((): LinkField => {
    const graphqlSource = this.datasource();
    const title = this.titleField();
    const href = graphqlSource?.url?.path;
    const rawJson = graphqlSource?.field?.jsonValue as { value?: string } | undefined;
    const titleValue = (title?.value != null ? String(title.value) : undefined) || rawJson?.value;
    return {
      value: {
        href,
        title: titleValue,
        text: titleValue,
      },
    };
  });

  readonly isEditing = computed(() => this.context.isEditing());
}

export default TitleComponent;
