// examples/angular/src/app/components/container.component.ts
import { Component, computed } from '@angular/core';
import { NgTemplateOutlet, NgStyle } from '@angular/common';
import { ScPlaceholderComponent } from '@sitecore-content-sdk/angular';
import { SxaComponent } from './content-sdk/sxa.component';

const mediaUrlPattern = /mediaurl="([^"]*)"/i;

@Component({
  selector: 'app-container',
  imports: [NgTemplateOutlet, NgStyle, ScPlaceholderComponent],
  host: {
    '[attr.class]': "('component container-default ' + styles().trim())",
    '[attr.id]': 'renderingId()',
  },
  template: `
    @if (needsWrapper()) {
    <div class="container-wrapper">
      <ng-container *ngTemplateOutlet="containerInner"></ng-container>
    </div>
    } @else {
    <ng-container *ngTemplateOutlet="containerInner"></ng-container>
    }

    <ng-template #containerInner>
      <div class="component-content" [ngStyle]="backgroundStyle()">
        @if (placeholderName()) {
        <sc-placeholder
          class="row"
          [name]="placeholderName()!"
          [rendering]="rendering()!"
        ></sc-placeholder>
        }
      </div>
    </ng-template>
  `,
})
export class ContainerComponent extends SxaComponent {
  readonly placeholderName = computed(() => {
    const id = this.params()?.DynamicPlaceholderId?.trim();
    return id ? `container-${id}` : '';
  });

  readonly needsWrapper = computed(() => {
    const tokens = this.styles()?.split(/\s+/).filter(Boolean) ?? [];
    return tokens.includes('container');
  });

  readonly backgroundStyle = computed((): { [key: string]: string } => {
    const backgroundImage = this.params()?.BackgroundImage;
    if (!backgroundImage || !mediaUrlPattern.test(backgroundImage)) {
      return {};
    }
    const mediaUrl = backgroundImage.match(mediaUrlPattern)?.at(1) ?? '';
    if (!mediaUrl) {
      return {};
    }
    return {
      backgroundImage: `url('${mediaUrl}')`,
    };
  });
}

export default ContainerComponent;

// examples/kit-nextjs-skate-park/src/components/container/Container.tsx
import React, { JSX } from 'react';
import componentMap from '.sitecore/component-map';
import { AppPlaceholder } from "@sitecore-content-sdk/nextjs";
import { ContainerProps } from './container.props';

const Container = ({
  params,
  rendering,
  page,
}: ContainerProps): JSX.Element => {
  const {
    styles,
    RenderingIdentifier: id,
    BackgroundImage: backgroundImage,
    DynamicPlaceholderId,
  } = params;
  const phKey = `container-${DynamicPlaceholderId}`;

  // Extract the mediaurl from rendering parameters
  const mediaUrlPattern = new RegExp(/mediaurl=\"([^"]*)\"/, "i");

  let backgroundStyle: { [key: string]: string } = {};

  if (backgroundImage && backgroundImage.match(mediaUrlPattern)) {
    const mediaUrl = backgroundImage.match(mediaUrlPattern)?.[1] || "";

    backgroundStyle = {
      backgroundImage: `url('${mediaUrl}')`,
    };
  }

  return (
    <section className={`component container-default ${styles}`} id={id}>
      <div className="component-content" style={backgroundStyle}>
        <div className="row">
          <AppPlaceholder
            name={phKey}
            rendering={rendering}
            page={page}
            componentMap={componentMap}
          />
        </div>
      </div>
    </section>
  );
};

export const Default = ({ params, rendering, page }: ContainerProps): JSX.Element => {
  const styles = params?.styles?.split(' ');

  return styles?.includes('container') ? (
    <div className="container-wrapper">
      <Container params={params} rendering={rendering} page={page} />
    </div>
  ) : (
    <Container params={params} rendering={rendering} page={page} />
  );
};
