// examples/kit-nextjs-skate-park/src/components/content-sdk/CdpPageView.tsx
'use client';
import { useEffect, JSX } from 'react';
import { CdpHelper, useSitecore } from '@sitecore-content-sdk/nextjs';
import { pageView } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';

/**
 * This is the CDP page view component.
 * It uses the Sitecore Cloud SDK to enable page view events on the client-side.
 * See Sitecore Cloud SDK documentation for details.
 * https://www.npmjs.com/package/@sitecore-cloudsdk/events
 */
const CdpPageView = (): JSX.Element => {
  const {
    page: { layout, siteName, mode },
  } = useSitecore();
  const { route, context } = layout.sitecore;

  /**
   * Determines if the page view events should be turned off.
   * IMPORTANT: You should implement based on your cookie consent management solution of choice.
   * By default it is disabled in development mode
   */
  const disabled = () => {
    return process.env.NODE_ENV === 'development';
  };

  useEffect(() => {
    // Do not create events in editing or preview mode or if missing route data
    if (!mode.isNormal || !route?.itemId) {
      return;
    }
    // Do not create events if disabled (e.g. we don't have consent)
    if (disabled()) {
      return;
    }

    const language = route.itemLanguage || config.defaultLanguage;
    const scope = config.personalize?.scope;

    const pageVariantId = CdpHelper.getPageVariantId(
      route.itemId,
      language,
      context.variantId as string,
      scope
    );
    // there can be cases where Events are not initialized which are expected to reject
    pageView({
      channel: 'WEB',
      currency: 'USD',
      page: route.name,
      pageVariantId,
      language,
    }).catch((e) => console.debug(e));
  }, [mode, route, context.variantId, siteName]);

  return <></>;
};

export default CdpPageView;

// examples/angular/src/app/components/content-sdk/cdp-page-view.component.ts
import { Component, effect, inject } from '@angular/core';
import {
  CdpHelper,
  SITECORE_ANALYTICS,
  SitecoreContextService,
} from '@sitecore-content-sdk/angular';
import config from 'sitecore.config';

/**
 * CDP page view component. Dispatches a Sitecore CDP page view event on initial load and on
 * every client-side navigation. Template-less — it only performs the side effect.
 *
 * page data comes from {@link SitecoreContextService}, dispatch goes through the {@link SITECORE_ANALYTICS} facade
 * Runs in browser only.
 *
 * See Sitecore Content SDK documentation for details:
 * https://www.npmjs.com/package/@sitecore-content-sdk/events
 */
@Component({
  selector: 'app-cdp-page-view',
  template: '',
})
export class CdpPageViewComponent {
  private readonly analytics = inject(SITECORE_ANALYTICS);
  private readonly context = inject(SitecoreContextService);

  constructor() {
    effect(() => {
      const page = this.context.page();
      // Do not create events in editing or preview mode, or if missing route data.
      if (!page || !page.mode.isNormal) {
        return;
      }
      const route = page.layout.sitecore.route;
      if (!route?.itemId) {
        return;
      }

      const language = page.locale || config.defaultLanguage;
      const pageVariantId = CdpHelper.getPageVariantId(
        route.itemId,
        language,
        page.layout.sitecore.context.variantId as string,
        config.personalize.scope
      );

      // Events may not be initialized (the façade is a no-op in dev / when Edge config is
      // missing, and swallows runtime failures at debug level).
      void this.analytics.pageView({
        channel: 'WEB',
        currency: 'USD',
        page: route.name,
        pageVariantId,
        language,
      });
    });
  }
}
